---
- name:         Ensure pip path is correctly set for debian9/10 ubuntu1804 and centos8
  set_fact:
    python_pip: /usr/local/bin/pip

- name:         Ensure pip path is correctly set for centos7
  set_fact:
    python_pip: /usr/bin/pip
  when:         ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name:         Ensure wheel, setuptools are in latest version
  pip:
    name:       [ wheel, setuptools ]
    extra_args: --user
    executable: "{{ python_pip }}"
    state:      latest
  become:       true
  become_user:  "{{ item }}"
  loop:         "{{ ansible_users|flatten(levels=1) }}"

- name:         Ensure ansible, ansible-lint and molecule are installed
  pip:
    name:       molecule
    executable: "{{ python_pip }}"
    extra_args: --user
  become:       true
  become_user:  "{{ item }}"
  loop:         "{{ ansible_users|flatten(levels=1) }}"
